spring:
  application:
    name: ordinaryroad-live-chat-client-example
tech:
  ordinaryroad:
    live:
      chat:
        client:
          example:
            client:
              config:
                bilibili:
                  # TODO 直播间id
                  roomId: 7777
                  # TODO 浏览器Cookie
                  cookie: ${bilibiliCookie:}
                douyu:
                  # TODO 直播间id
                  roomId: 74751
                  # TODO 浏览器Cookie
                  cookie: ${douyuCookie:}
                kuaishou:
                  # TODO 直播间id
                  roomId: KPL704668133
                  # TODO 浏览器Cookie
                  cookie: ${kuaishouCookie:}
logging:
  level:
    tech.ordinaryroad: INFO
    io.netty: INFO